### ISSUE TITLE
TWL06.dawg is less than half the size of the TWL06.dawg used by Quackle

### ISSUE THREAD

**Issue by onzie9** [AndrasKovacs/dawg-gen#1]
I can't get the .dawg files created here to work with Quackle, and after a little digging, I see that the .dawg files created here are quite a bit smaller than the ones Quackle uses.  Quackle's provided twl06.dawg is 1.8MB, and the output here is 900kb. I'm not sure if that means anything bad, but I wanted to point it out.

**Comment by AndrasKovacs** [comment]
It seems that I always do a validation pass on the output (read out all the words from the dawg and compare with the input dictionary), so the data is probably OK. Probably there's some mismatch in actual and expected binary layout, which causes something to break (note that lists of child dawg nodes are not ordered!). The smallness of the output is expected; I remember making an effort to do more aggressive minimization than what I saw in other implementations.
